import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

//Font awesome imports
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import {faLocationDot, faMapLocationDot} from "@fortawesome/free-solid-svg-icons";

import MainButton from "../components/mainbutton";

export default function Home() {

    return (
        <div>
            {/*<Head>*/}
            {/*    <title>Create Next App</title>*/}
            {/*    <meta name="description"*/}
            {/*          content="Generated by create next app"/>*/}
            {/*    <link rel="icon"*/}
            {/*          href="/favicon.ico"/>*/}
            {/*</Head>*/}

            <div className ={styles.menuBox}>
                <h1>Andrew McDonald</h1>
                <div className={styles.currentLocationBox}>
                    <h3><FontAwesomeIcon className={styles.icons} icon={faLocationDot} style={{ fontSize: 25, color: '9EBD6E'}} />Melbourne, Australia</h3>
                </div>
                <MainButton title={'My Story'}/>
                <MainButton title={'Career Timeline'}/>
                <MainButton title={'Detailed CV'}/>
                <MainButton title={'Example Web Design'}/>
                <MainButton title={'Digital Artwork'}/>
                <MainButton title={'Get In Touch'}/>
            </div>


            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg"
                   alt="Vercel Logo"
                   width={72}
                   height={16}/>
          </span>
                </a>
            </footer>
        </div>
    )
}
